### ISSUE TITLE
Doesn't look legit - want to share details?

### ISSUE THREAD

**Issue by rglastra** [nh2/gmail-spamfilters-paypal-security-messages#1]
Are you sure this email is legit? Do you want to share the headers?

The quotation marks around 'service@paypal.co.uk' make me suspect they used a legit PayPal email address as the From: name, but sent it from a different location.

Additionally, if it was a legit PayPal email they would greet you with first/lastname.

**Comment by ac427** [comment]
It is not legit. It is a spam mail. Why will PayPal send it through some other relay server. If you look at the screenshot it will show ` via`

**Comment by nh2** [comment]
It's legit.

Google has contacted me since, I've provided some data, and the conclusion is:

> our analysts are taking a look, it seems there was nothing wrong on Paypal's end or your domain configuration. They have already deployed a short-term fix for this issue, you should not have this issue specifically with paypal again. We're still looking into whether we can use this to improve the quality of our filters in general.

---

Addressing other coments:

> It is not legit. It is a spam mail. Why will PayPal send it through some other relay server. If you look at the screenshot it will show ` via`

@ac427 This was already [explained in the HN thread](https://news.ycombinator.com/item?id=19100315).

Also, I know that I performed an action that resulted in this email (I added a new user to the account).

**Comment by nh2** [comment]
I have now added Google's response to the README:

https://github.com/nh2/gmail-spamfilters-paypal-security-messages/blob/master/README.md#update-googles-response

Closing, please repoen in case something isn't clear yet.
