### ISSUE TITLE
paypal is notoriously spammy

### ISSUE THREAD

**Issue by thedch** [nh2/gmail-spamfilters-paypal-security-messages#2]
as others have noted, this looks like a fraudulent email (check the headers) -- even if it isn't, paypal is notorious for spamming their users, them being marked as spam is a result of their very poor email practice -- see: https://twitter.com/nearlydaniel/status/1090299343272374272

**Comment by nh2** [comment]
Copying over the response from Google from https://github.com/nh2/gmail-spamfilters-paypal-security-messages/issues/1#issuecomment-464490453:

> our analysts are taking a look, it seems there was nothing wrong on Paypal's end or your domain configuration. They have already deployed a short-term fix for this issue, you should not have this issue specifically with paypal again. We're still looking into whether we can use this to improve the quality of our filters in general.

Of course that doesn't preclude that PayPal has poor email practice, but at least Google seems to think that it's not PayPal's fault in this case.

**Comment by nh2** [comment]
Added commit with Google's response:

https://github.com/nh2/gmail-spamfilters-paypal-security-messages/commit/d985247e8a1f15e5e85cd4c5a220b05e1e41cc66

Closing, please reopen if something remains unclear.
